# This is a basic workflow to help you get started with Actions
name: Readme Update

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datetime
          pip install feedparser
      
      - name: Update README
        run: python update-post.py

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Files have changed"
      - name: Set Commit Message
        run: |
          COMMIT_MESSAGE="[auto] $(date -u +"%Y-%m-%d") Blog Posting List Update"

      - name: Output Message If No Changes
        if: steps.check_changes.outputs.code == 0
        run: echo "No changes to commit."
          
      - name: Commit README
        if: steps.check_changes.outputs.code != 0
        run: |
          git config --global user.email "67352902+devyuseon@users.noreply.github.com"
          git config --global user.name "yuseonLim"
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
