# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Update Post to README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "* * * * *"
    
permissions:
   contents: write
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install import feedparser
        pip install os
        pip install datetime
    - name: Update README
      run: python update-post.py
    - name: Commit README
      run: |
        git add .
        git diff
        git commit -m "[auto] $(date +'%Y-%m-%d') Blog posting list update"
        git push
      with:
        user: __token__
        password: ${{ secrets.MY_TOKEN }}
